---
 - hosts: localhost
   vars_files:
     - /home/ec2-user/playbooks/vault_password.yml
   gather_facts: false

   tasks:
    - name: stage runner playbook
      ansible.builtin.expect:
       command: ansible-playbook /home/ec2-user/playbooks/PRODcontainer.yml --ask-vault-pass
       responses:
         Vault password: \"{{ vault_pass }}\"
       timeout: 600